### ISSUE TITLE
Linking SDL2 to projects

### ISSUE THREAD

**Issue by MIfeanyi** [ZoogieZork/SDL2-Package#4]
Hello, I'm trying to Link SDL2 to use for my game but I dont know the correct flags to use to link my project. the IDE I'm using is QT Creator.
![sdl2test pro - sdl2test - qt creator_507](https://f.cloud.github.com/assets/2005586/1202733/9f4b40fa-2548-11e3-9fb4-52c8103a1598.png)

**Comment by ZoogieZork** [comment]
I'm not familiar with QT Creator, but at first glance that looks like it should work.

The SDL2 packages ship with pkg-config files, so give this a try:

```
CONFIG += link_pkgconfig
PKGCONFIG += sdl2 SDL2_image SDL2_mixer SDL2_ttf
```

If that still doesn't work, you can try running pkg-config from a terminal to get the full linker options:

```
pkg-config --libs sdl2 SDL2_image SDL2_mixer SDL2_ttf
```

**Comment by MIfeanyi** [comment]
I found the issue. those flags are correct but I still had the SDL1.2 #include in the source ( converting 1.2 code to 2.0)

**Comment by ZoogieZork** [comment]
Ah, good to know.
